
objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/func_cmd/fm_func.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/func_cmd/rtc_func.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/func_cmd/music_func.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/func_cmd/linein_func.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/func_cmd/bt_func.o \

