includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting_opt/ \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting_opt/smartbox_setting_opt.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting_opt/smartbox_setting_sync.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting_opt/smartbox_adv_bluetooth.o \
