

objs += \

ifeq ($(APP_CASE),earphone)
objs += \
	  $(ROOT)/cpu/$(CPU)/audio_effect/eq_config.o \

else ifeq ($(APP_CASE),soundbox)
objs += \
	  $(ROOT)/cpu/$(CPU)/audio_effect/eq_config.o \

else ifeq ($(APP_CASE),watch)
objs += \
	  $(ROOT)/cpu/$(CPU)/audio_effect/eq_config.o \

else ifeq ($(APP_CASE),dongle)
objs += \

endif
