
objs += \
	$(ROOT)/apps/$(APP_CASE)/soundcard/soundcard.o \
	$(ROOT)/apps/$(APP_CASE)/soundcard/lamp.o \
	$(ROOT)/apps/$(APP_CASE)/soundcard/notice.o \
	$(ROOT)/apps/$(APP_CASE)/soundcard/peripheral.o \

