includes += \
	-I$(ROOT)/apps/soundbox/include/ui/color_led \


objs += \
	$(ROOT)/apps/$(APP_CASE)/ui/color_led/color_led_app.o \
	$(ROOT)/apps/$(APP_CASE)/ui/color_led/color_led_table.o \
	$(ROOT)/apps/$(APP_CASE)/ui/color_led/driver/color_led.o \
	$(ROOT)/apps/$(APP_CASE)/ui/color_led/driver/color_led_driver.o \

