

ifeq ($(APP_CASE),soundbox)
objs += \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/ui_sys_param_api.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/lyrics_api.o \

include $(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/Makefile


endif


