includes += \
	-I$(ROOT)/apps/common/third_party_profile/jieli/trans_data_demo/ \

objs += \
	$(ROOT)/apps/$(APP_CASE)/third_party_profile/trans_data_demo/trans_data_demo.o \
	$(ROOT)/apps/$(APP_CASE)/third_party_profile/ancs_client_demo/ancs_client_demo.o \


includes += \
	-I$(ROOT)/apps/$(APP_CASE)/include/third_party_profile/gma/ \
	-I$(ROOT)/apps/$(APP_CASE)/include/third_party_profile/dma/ \

objs += \
	$(ROOT)/apps/$(APP_CASE)/third_party_profile/gma/gma_app_main.o \
	$(ROOT)/apps/$(APP_CASE)/third_party_profile/dma/dma_app_main.o \


