includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_update/ \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_update/smartbox_update.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_update/smartbox_update_tws.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_update/rcsp_ch_loader_download.o \
