includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/ \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_eq_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_high_low_vol_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_music_info_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_vol_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_color_led_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_karaoke_eq_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_karaoke_setting.o \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/adv_bt_name_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/adv_key_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/adv_led_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/adv_mic_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/adv_time_stamp_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/adv_work_setting.o \

include $(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_misc_setting/Makefile
