includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/ \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/bt_manage/bt_trans_data/ \


objs += \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/cmd_recieve.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/cmd_recieve_no_respone.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/cmd_respone.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/data_recieve.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/data_recieve_no_respone.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/data_respone.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/cmd_user.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/config.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_task.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/event.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/cmd_data_deal/command.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/feature.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/function.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_rcsp_manage.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/switch_device.o \
	$(ROOT)/apps/$(APP_CASE)/smartbox/browser/browser.o \

include $(ROOT)/apps/$(APP_CASE)/smartbox/func_cmd/Makefile
include $(ROOT)/apps/$(APP_CASE)/smartbox/bt_manage/Makefile
include $(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/Makefile
include $(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting_opt/Makefile
include $(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_update/Makefile
include $(ROOT)/apps/$(APP_CASE)/smartbox/file_transfer/Makefile
