includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/file_transfer/ \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/file_transfer/file_transfer.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/file_transfer/file_delete.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/file_transfer/dev_format.o \

