

ifeq ($(APP_CASE),soundbox)
objs += \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/bt_action.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/fm_action.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/clock_action.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/music_action.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/file_brower.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/system_action.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/record_action.o \
		$(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/linein_action.o \
		# $(ROOT)/apps/$(APP_CASE)/ui/lcd/STYLE_02/main_action.o \

endif
