includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_misc_setting \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_misc_setting/smartbox_misc_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_misc_setting/smartbox_misc_reverbration_setting.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/smartbox_setting/smartbox_misc_setting/smartbox_misc_drc_setting.o \
