includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/bt_manage/ \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/bt_manage/smartbox_bt_manage.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/bt_manage/bt_trans_data/le_smartbox_module.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/bt_manage/bt_trans_data/le_smartbox_adv.o \

